[package]
name = "nexcrawl_html"
version = "0.1.0"
edition = "2024"
description = "HTML processing library for NexCrawl"
readme = "README.md"

[dependencies]
ammonia = "4.1.1"
html5ever = "0.35.0"
log = "0.4.28"
markup5ever_rcdom = "0.35.0"

[dev-dependencies]
clippy = "0.0.302"
